<?php

/**
* autoload.php @generated by Fabio Alemida
*
* @Example of use / Exemplo de uso
*
* require './PhpEntityDbContext/autoload.php';
* $phpEntityDbContext = PhpEntityDbContext\PhpEntityDbContextSetting::InitialSetting("./Models", $_ENV["DB_HOST"], $_ENV["DB_NAME"], $_ENV["DB_USER"], $_ENV["DB_PASSWORD"]);
*
* $entity = new EntityDbContext(new Model);
* $entity->ToList();
*/

require_once __DIR__ .'./EntityDbContext/EntityDbContexSetting.php';